





spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 8dc0da4473a95d93f7e237da8f6ca7c6
            redirect-uri: http://34.64.180.211:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
            - profile_nickname
            - account_email

        provider:
            kakao:
              authorization-uri: https://kauth.kakao.com/oauth/authorize
              token-uri: https://kauth.kakao.com/oauth/token
              user-info-uri: https://kapi.kakao.com/v2/user/me
              user-name-attribute: id
#
#    jpa:
#      open-in-view: true
#      database-platform: org.h2.Driver
#      show-sql: true
#      properties:
#        hibernate.format_sql: true
#        hibernate.use_sql_comments: true
#      hibernate:
#        ddl-auto: create
#
#    datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://34.22.75.189:3306/notodo?useSSL=false&serverTimezone=UTC
#    username: hyuk
#    password: Chlgurtns98!
